In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/Users/tamannarawat/Downloads/blinkit_clean.csv")

In [4]:
df.head()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0

In [5]:
df.tail()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
8518,low fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,164.5526,4.0
8519,low fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,NaN,241.6828,4.0
8520,low fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,NaN,86.6198,4.0
8521,reg,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,NaN,97.8752,4.0
8522,reg,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,112.2544,4.0

In [6]:
df.shape

(8523, 12)

In [12]:
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='object')

In [13]:
df.describe

<bound method NDFrame.describe of      Item Fat Content Item Identifier              Item Type  \
0             Regular           FDX32  Fruits and Vegetables
1             Low Fat           NCB42     Health and Hygiene
2             Regular           FDR28           Frozen Foods
3             Regular           FDL50                 Canned
4             Low Fat           DRI25            Soft Drinks
...               ...             ...                    ...
8518          low fat           NCT53     Health and Hygiene
8519          low fat           FDN09            Snack Foods
8520          low fat           DRE13            Soft Drinks
8521              reg           FDT50                  Dairy
8522              reg           FDM58            Snack Foods

      Outlet Establishment Year Outlet Identifier Outlet Location Type  \
0                          2012            OUT049               Tier 1
1                          2022            OUT018               Tier 3
2                          2016            OUT046               Tier 1
3                          2014            OUT013               Tier 3
4                          2015            OUT045               Tier 2
...                         ...               ...                  ...
8518                       2018            OUT027               Tier 3
8519                       2018            OUT027               Tier 3
8520                       2018            OUT027               Tier 3
8521                       2018            OUT027               Tier 3
8522                       2018            OUT027               Tier 3

     Outlet Size        Outlet Type  Item Visibility  Item Weight     Sales  \
0         Medium  Supermarket Type1         0.100014        15.10  145.4786
1         Medium  Supermarket Type2         0.008596        11.80  115.3492
2          Small  Supermarket Type1         0.025896        13.85  165.0210
3           High  Supermarket Type1         0.042278        12.15  126.5046
4          Small  Supermarket Type1         0.033970        19.60   55.1614
...          ...                ...              ...          ...       ...
8518      Medium  Supermarket Type3         0.000000          NaN  164.5526
8519      Medium  Supermarket Type3         0.034706          NaN  241.6828
8520      Medium  Supermarket Type3         0.027571          NaN   86.6198
8521      Medium  Supermarket Type3         0.107715          NaN   97.8752
8522      Medium  Supermarket Type3         0.000000          NaN  112.2544

      Rating
0        5.0
1        5.0
2        5.0
3        5.0
4        5.0
...      ...
8518     4.0
8519     4.0
8520     4.0
8521     4.0
8522     4.0

[8523 rows x 12 columns]>

In [14]:
df.isnull().sum()

Item Fat Content                0
Item Identifier                 0
Item Type                       0
Outlet Establishment Year       0
Outlet Identifier               0
Outlet Location Type            0
Outlet Size                     0
Outlet Type                     0
Item Visibility                 0
Item Weight                  1463
Sales                           0
Rating                          0
dtype: int64

In [15]:
(df.isnull().sum()/len(df))*100

Item Fat Content              0.000000
Item Identifier               0.000000
Item Type                     0.000000
Outlet Establishment Year     0.000000
Outlet Identifier             0.000000
Outlet Location Type          0.000000
Outlet Size                   0.000000
Outlet Type                   0.000000
Item Visibility               0.000000
Item Weight                  17.165317
Sales                         0.000000
Rating                        0.000000
dtype: float64

In [18]:
df.duplicated().all()

np.False_

In [19]:
df.nunique()

Item Fat Content                5
Item Identifier              1559
Item Type                      16
Outlet Establishment Year       9
Outlet Identifier              10
Outlet Location Type            3
Outlet Size                     3
Outlet Type                     4
Item Visibility              7880
Item Weight                   415
Sales                        5938
Rating                         39
dtype: int64

In [20]:
df.dtypes

Item Fat Content              object
Item Identifier               object
Item Type                     object
Outlet Establishment Year      int64
Outlet Identifier             object
Outlet Location Type          object
Outlet Size                   object
Outlet Type                   object
Item Visibility              float64
Item Weight                  float64
Sales                        float64
Rating                       float64
dtype: object

In [21]:
df['Sales'].sum()

np.float64(1201681.4928)

In [22]:
df['Sales'].mean()

np.float64(140.99278338613163)

In [23]:
df.groupby("Item Type")['Sales'].sum().sort_values(ascending=False)

Item Type
Fruits and Vegetables    178124.0810
Snack Foods              175433.9224
Household                135976.5254
Frozen Foods             118558.8814
Dairy                    101276.4616
Canned                    90706.7290
Baking Goods              81894.7364
Health and Hygiene        68025.8388
Meat                      59449.8638
Soft Drinks               58514.1670
Breads                    35379.1198
Hard Drinks               29334.6806
Others                    22451.8916
Starchy Foods             21880.0274
Breakfast                 15596.6966
Seafood                    9077.8700
Name: Sales, dtype: float64

In [25]:
df.groupby("Outlet Identifier")["Sales"].sum().sort_values(ascending=False)

Outlet Identifier
OUT035    133103.9070
OUT046    132113.3698
OUT013    131809.0156
OUT018    131477.7764
OUT045    130942.7802
OUT027    130714.6746
OUT049    130476.8598
OUT017    129103.9604
OUT010     78131.5666
OUT019     73807.5824
Name: Sales, dtype: float64

In [26]:
df.groupby("Outlet Type")["Sales"].sum().sort_values(ascending=False)

Outlet Type
Supermarket Type1    787549.8928
Grocery Store        151939.1490
Supermarket Type2    131477.7764
Supermarket Type3    130714.6746
Name: Sales, dtype: float64

In [27]:
df.groupby("Outlet Size")["Sales"].sum().sort_values(ascending=False)

Outlet Size
Medium    507895.7364
Small     444794.1704
High      248991.5860
Name: Sales, dtype: float64

In [29]:
df.groupby("Item Fat Content")["Sales"].sum().sort_values(ascending=False)

Item Fat Content
Low Fat    717390.8474
Regular    409413.1234
LF          43857.1082
reg         15948.6810
low fat     15071.7328
Name: Sales, dtype: float64

In [31]:
df.groupby("Item Type")["Rating"].mean().sort_values(ascending=False)

Item Type
Meat                     4.023059
Household                3.998681
Canned                   3.994299
Health and Hygiene       3.986154
Baking Goods             3.983025
Frozen Foods             3.971145
Dairy                    3.965836
Seafood                  3.959375
Fruits and Vegetables    3.956169
Others                   3.954438
Snack Foods              3.948917
Breakfast                3.932727
Soft Drinks              3.920674
Starchy Foods            3.920270
Hard Drinks              3.907477
Breads                   3.881275
Name: Rating, dtype: float64

In [32]:
df.groupby("Item Identifier")["Sales"].sum().sort_values(ascending=False).head(10)

Item Identifier
FDU12    2371.0112
FDT07    2306.8970
NCQ06    2294.7126
FDL58    2111.6544
NCB31    2104.7280
FDX31    2104.4622
FDF05    2103.1280
FDR59    2096.5752
FDP28    2087.8488
FDA04    2072.0696
Name: Sales, dtype: float64

In [36]:
df.groupby("Outlet Identifier")["Sales"].sum().idxmax()

'OUT035'

# Numpy

In [38]:
np.mean(df['Sales'])

np.float64(140.99278338613163)

In [39]:
np.median(df['Sales'])

np.float64(143.0128)

In [40]:
np.std(df['Sales'])

np.float64(62.27141334999408)

In [41]:
np.min(df['Sales'])

np.float64(31.29)

In [42]:
np.max(df['Sales'])

np.float64(266.8884)

In [43]:
np.percentile(df['Sales'],25)

np.float64(93.8265)

In [45]:
np.percentile(df['Sales'],50)

np.float64(143.0128)

In [44]:
np.percentile(df['Sales'],75)

np.float64(185.6437)

# pandas analysis

In [48]:
avg_sales=df['Sales'].mean()
df[df['Sales']>avg_sales]

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
9,Low Fat,FDX25,Canned,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.101562,NaN,181.9292,5.0
11,Low Fat,NCU41,Health and Hygiene,2017,OUT035,Tier 2,Small,Supermarket Type1,0.052045,18.85,192.1846,5.0
13,Low Fat,NCR54,Household,2014,OUT013,Tier 3,High,Supermarket Type1,0.090487,16.35,195.2110,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8512,Regular,FDY33,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.096730,NaN,159.0262,4.0
8515,low fat,FDK38,Canned,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.053032,NaN,149.1734,4.0
8517,low fat,FDG32,Fruits and Vegetables,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.175143,NaN,222.3772,4.0
8518,low fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,164.5526,4.0
8519,low fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,NaN,241.6828,4.0

In [4]:
df.nlargest(5,'Rating')[['Item Identifier','Item Type','Rating','Sales']]

  Item Identifier              Item Type  Rating     Sales
0           FDX32  Fruits and Vegetables     5.0  145.4786
1           NCB42     Health and Hygiene     5.0  115.3492
2           FDR28           Frozen Foods     5.0  165.0210
3           FDL50                 Canned     5.0  126.5046
4           DRI25            Soft Drinks     5.0   55.1614

In [6]:
df.groupby('Outlet Identifier')['Sales'].mean().sort_values(ascending=False)

Outlet Identifier
OUT035    143.122481
OUT046    142.057387
OUT018    141.678638
OUT013    141.425982
OUT045    140.950248
OUT010    140.777597
OUT049    140.297699
OUT027    139.801791
OUT019    139.787088
OUT017    139.421124
Name: Sales, dtype: float64

In [7]:
df['Item Type'].value_counts()

Item Type
Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: count, dtype: int64

In [9]:
df.groupby('Outlet Type')['Rating'].mean().sort_values(ascending=False)

Outlet Type
Grocery Store        3.985873
Supermarket Type2    3.971228
Supermarket Type1    3.963242
Supermarket Type3    3.952941
Name: Rating, dtype: float64

In [10]:
df.groupby('Outlet Identifier')['Item Identifier'].count().sort_values(ascending=False)

Outlet Identifier
OUT027    935
OUT013    932
OUT035    930
OUT046    930
OUT049    930
OUT045    929
OUT018    928
OUT017    926
OUT010    555
OUT019    528
Name: Item Identifier, dtype: int64

In [13]:
df.groupby('Item Identifier')['Item Visibility'].max()

Item Identifier
DRA12    0.068535
DRA24    0.069909
DRA59    0.223985
DRB01    0.082367
DRB13    0.011791
           ...
NCZ30    0.043828
NCZ41    0.064786
NCZ42    0.011352
NCZ53    0.040970
NCZ54    0.145952
Name: Item Visibility, Length: 1559, dtype: float64

In [14]:
df['Sales Category']=df['Sales'].apply(lambda x : 'High' if x>=200 else'Medium' if 100<=x<=200 else 'Low')

In [16]:
sales_by_category = df.groupby("Item Type")["Sales"].sum()

percentage = (sales_by_category / sales_by_category.sum()) * 100

percentage.sort_values(ascending=False)

Item Type
Fruits and Vegetables    14.822903
Snack Foods              14.599037
Household                11.315521
Frozen Foods              9.866082
Dairy                     8.427896
Canned                    7.548317
Baking Goods              6.815012
Health and Hygiene        5.660888
Meat                      4.947223
Soft Drinks               4.869357
Breads                    2.944135
Hard Drinks               2.441136
Others                    1.868373
Starchy Foods             1.820784
Breakfast                 1.297906
Seafood                   0.755431
Name: Sales, dtype: float64

In [17]:
df.to_csv("blinkit_cleaned.csv", index=False)